image: node:14.18.2

variables:
  DEFAULT_REGION: ap-south-1
  PROJECT_NAME: kaldariapp-env
  APP_NAME: kaldariapp-env
  BUCKET_NAME: elasticbeanstalk-ap-south-1-680146243022

stages:
  - deploy

before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install zip
  - apt-get install unzip
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install

deploy:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    ENV: Kaldariappenv-env
  script:
    - npm install
    - npm run build
    - npm run dist
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $DEFAULT_REGION
    - aws s3 cp build/$PROJECT_NAME.zip s3://$BUCKET_NAME/$PROJECT_NAME-$CI_PIPELINE_ID.zip
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $APP_NAME-$CI_PIPELINE_ID --source-bundle S3Bucket=$BUCKET_NAME,S3Key=$PROJECT_NAME-$CI_PIPELINE_ID.zip --region $DEFAULT_REGION
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name $ENV --version-label $APP_NAME-$CI_PIPELINE_ID --region $DEFAULT_REGION
    - echo "Health is Grey, please check the AWS console"
  only:
    refs:
      - main